### ISSUE TITLE
Enable scroll for the table of content.

### ISSUE THREAD

**Issue by zubayrrr** [phartenfeller/gatsby-philipps-foam-theme#4]
Scrollable table of content, thanks.

**Comment by phartenfeller** [comment]
Oh sorry I somehow missed this issue. I saw that you forked it, so are you currently working on it?

**Comment by zubayrrr** [comment]
> Oh sorry I somehow missed this issue. I saw that you forked it, so are you currently working on it?

I did try but I couldnt figure it out :|

**Comment by phartenfeller** [comment]
I will take a look at it on the weekend 😃

**Comment by phartenfeller** [comment]
Should be fixed now in version 0.1.0 👍🏽
