### ISSUE TITLE
How to avoid building pages inside a specific folder

### ISSUE THREAD

**Issue by t2hv33** [phartenfeller/gatsby-philipps-foam-theme#5]
Hi @phartenfeller 
As a user, I don't want to publish private notes Foam inside a specific folder.
My structure folders tree
```
|--_layouts
|--docs
|--private #don't want to publish this folder
|--notes
```
I have a lot of folders same level with docs
After run `yarn develop` gatsby also renders all `private` notes on the `public` folder.
My expectation here is: `private` folders do not render.
How to do that? Is there a way to avoid building pages with certain paths in Gatsby?
Thanks,

**Comment by phartenfeller** [comment]
Hi!

There is already an option for it that wasn't documented (till now 😄).

You can add an ignore array to your config and add your "private" folder:

   ```js
   plugins: [
    {
      resolve: `gatsby-philipps-foam-theme`,
      options: {
        rootNote: "/readme",
        contentPath: "/",
        ignore: [
          "**/private/**",
        ],
      },
    },
   ],
   ```

Links to private pages for now result in a 404. I may remove the HTML `a` tag and make it outstanding that the link won't work in the future.

**Comment by t2hv33** [comment]
Hi @phartenfeller 
It's working like a charm when I use `"**/private/**/*"`, all notes inside displayed 404, can't search.
` "**/private/**"`: Pages inside `private` can search
- You should update document for this:  "**/private/**/*" instead use  "**/private/**"
- Note: You should create an issue for tracking this in the future: may remove the HTML a tag and make it outstanding that the link won't work
```
plugins: [
    {
      resolve: `gatsby-philipps-foam-theme`,
      options: {
        rootNote: "/readme",
        contentPath: `${__dirname}/..`,
        ignore: [
          "**/_layouts/**",
          "**/.git/**",
          "**/.github/**",
          "**/.vscode/**",
          "**/private/**/*", #using this for ignore all notes inside sub folder
        ],
      },
    },
  ],
```
Regards,

**Comment by phartenfeller** [comment]
Thanks for the info, I changed the readme!

I created #6 to track removing links to excluded pages.

Regards,
Philipp
